---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: vrf-casdhsf
  annotations:
    kubernetes.io/ingress.class: default
spec:
  # ingressClassName: default
  rules:
  # https://vrf-casdhsf.k8s.vrfgstest.org/
  - host: "vrf-casdhsf.k8s.vrfgstest.org"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: example-ingress
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: example-ingress
  namespace: vrf-casdhsf
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    # this selector points to pods we want to target
    app: deploy-example
